services:
  web:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "$PORTAINER_WEB_PORT:9000"
      - "$PORTAINER_AGENT_PORT:8000"
    depends_on:
      - db
    environment:
      - LOG_LEVEL=info
      - PORTAINER_DB_CONNECTION=postgres://portainer:$POSTGRES_PASSWORD@db:5432/portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer_network

  db:
    image: postgres:latest
    container_name: portainer_db
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: portainer
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - portainer_network

  agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_network

volumes:
  portainer_data:
  db_data:

networks:
  portainer_network:
    driver: bridge
